version: "3.5"

x-pcts-crawlers-api-template:
  &pcts-crawlers-api-template
  restart: unless-stopped
  build:
    context: .
  image: pcts-crawlers-api
  env_file: dev-env
  networks:
    - pcts-network
  depends_on:
    pcts-crawlers-postgres:
      condition: service_healthy
  volumes:
    - .:/app
    - pip-cache:/usr/local/lib/python3.8/site-packages

services:
  pcts-crawlers-postgres:
    image: postgres:13
    container_name: pcts-crawlers-postgres
    hostname: pcts-crawlers-postgres
    restart: unless-stopped
    env_file: dev-env
    ports:
        - 5432:5432
    networks:
      - pcts-network
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 5s
        retries: 5
    restart: unless-stopped
    volumes:
    - pcts-crawlers-postgres-data:/var/lib/postgresql/data

  pcts-crawlers-rabbitmq:
    image: rabbitmq:3.9.7
    container_name: pcts-crawlers-rabbitmq
    hostname: pcts-crawlers-rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
    networks:
      - pcts-network
    volumes:
      - pcts-crawlers-rabbitmq-data:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 3

  # PCTS CRAWLERS DJANGO API ==============================================================================
  pcts-crawlers-api:
    container_name: pcts-crawlers-api
    <<: *pcts-crawlers-api-template
    ports:
      - 8002:8002
    command: ["sh", "scripts/start_dev.sh"]
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8002/api"]
      interval: 10s
      retries: 5
    depends_on:
      pcts-crawlers-postgres:
        condition: service_healthy

  pcts-crawlers-celery:
    <<: *pcts-crawlers-api-template
    container_name: pcts-crawlers-celery
    command: ["sh", "scripts/start_celery.sh"]
    depends_on:
      pcts-crawlers-rabbitmq:
        condition: service_healthy
      pcts-crawlers-api:
        condition: service_healthy

  pcts-crawlers-celery-scheduler:
    <<: *pcts-crawlers-api-template
    container_name: pcts-crawlers-celery-scheduler
    command: ["sh", "scripts/start_celery_scheduler.sh"]
    depends_on:
      pcts-crawlers-api:
        condition: service_healthy

  pcts-crawlers-celery-flower:
    <<: *pcts-crawlers-api-template
    container_name: pcts-crawlers-celery-flower
    ports:
      - 5555:5555
    command: ["sh", "scripts/start_celery_flower.sh"]
    depends_on:
      pcts-crawlers-api:
        condition: service_healthy
  # =======================================================================================================

volumes:
  pcts-crawlers-postgres-data:
    name: pcts-crawlers-postgres-data
  pip-cache:
    name: pcts-crawlers-api-pip-cache
  pcts-crawlers-rabbitmq-data:
    name: pcts-crawlers-rabbitmq-data

networks:
  pcts-network:
    name: pcts-network
    driver: bridge
