version: "3.5"
services:
  pcts-scrapers-splash:
    hostname: pcts-scrapers-splash
    image: scrapinghub/splash
    container_name: pcts-scrapers-splash
    ports:
      - 8050:8050
    networks:
      - pcts-network
    command: "--disable-private-mode"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050"]
      interval: 30s
      retries: 5
  pcts-scrapers-api:
    container_name: pcts-scrapers-api
    # restart: unless-stopped
    build: .
    image: pcts-scrapers-api
    # env_file: dev-env
    environment:
      PROJECT_ENV_EXECUTOR: "DOCKER"
      PCTS_SCRAPERS_SPLASH_HOST: pcts-scrapers-splash
    ports:
      - 8002:8002
    networks:
      - pcts-network
    # command: ["sh", "scripts/start_dev.sh"]
    command: ["python", "run_scrapers.py"]
    depends_on:
      pcts-scrapers-splash:
        condition: service_healthy
    volumes:
      - .:/app
      - pip-cache:/usr/local/lib/python3.8/site-packages

volumes:
  pip-cache:
    name: pcts-scrapers-api-pip-cache

networks:
  pcts-network:
    name: pcts-network
    driver: bridge
