version: "3.5"
services:
  splash:
    image: scrapinghub/splash
    container_name: pcts-scraper-splash
    ports:
      - 8050:8050
    command: "--disable-private-mode"
  pcts-scraper:
    container_name: pcts-scraper
    # restart: unless-stopped
    build: .
    image: pcts-scraper
    # env_file: dev-env
    command: "echo 'Hello World'"
    networks:
      - pcts-network
    volumes:
      - .:/app
      - pip-cache:/usr/local/lib/python3.8/site-packages

volumes:
  pip-cache:
    name: pcts-scraper-pip-cache

networks:
  pcts-network:
    name: pcts-network
    driver: bridge
