# Generated by Django 3.2.9 on 2021-11-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawler',
            name='contains_dynamic_js_load',
        ),
        migrations.RemoveField(
            model_name='crawler',
            name='retries',
        ),
    ]
