# Generated by Django 3.2.7 on 2021-09-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_root', models.CharField(max_length=1024, verbose_name='Root Url')),
                ('site_name', models.CharField(max_length=50, verbose_name='Site Name')),
                ('next_button_xpath', models.CharField(max_length=240, verbose_name='Next Button (XPATH)')),
                ('pagination_retries', models.IntegerField(default=1)),
                ('pagination_delay', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
