# Generated by Django 3.2.8 on 2021-10-22 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, unique=True, verbose_name='Site Name')),
                ('url_root', models.CharField(max_length=1024, unique=True, verbose_name='Root Url')),
                ('task_name_prefix', models.CharField(max_length=50, unique=True, verbose_name='Task Name Prefix')),
                ('js_search_steps', models.JSONField(null=True, verbose_name='JS Search Steps (JSON List of Objects (elem_type, xpath, action))')),
                ('next_button_xpath', models.CharField(max_length=500, null=True, verbose_name='Next Button XPATH')),
                ('allowed_domains', models.JSONField(null=True, verbose_name='Allowed Domains (JSON List of strings)')),
                ('allowed_paths', models.JSONField(null=True, verbose_name='Allowed Paths (JSON List of strings)')),
                ('pagination_retries', models.IntegerField(default=3, null=True, verbose_name='Pagination Retries')),
                ('pagination_delay', models.IntegerField(default=3, null=True, verbose_name='Pagination Delay')),
                ('page_load_timeout', models.IntegerField(default=3, null=True, verbose_name='Page Load Delay')),
                ('restrict_xpaths', models.JSONField(null=True, verbose_name='Restrict by Xpath (JSON List of strings)')),
                ('restrict_css', models.JSONField(null=True, verbose_name='Restrict by CSS (Json List of strings)')),
                ('content_xpath', models.JSONField(null=True, verbose_name='Content XPATH (JSON Object (any key-value))')),
                ('query_string_params', models.JSONField(null=True, verbose_name='Query String Params (JSON List Object (param, value))')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperExecutionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='Task Name')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Start Datetime')),
                ('finish_datetime', models.DateTimeField(null=True, verbose_name='End Datetime')),
                ('status', models.IntegerField(choices=[(1, 'STARTED'), (2, 'SUCCESS'), (3, 'FAILED')], default=1, verbose_name='Execution Status')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_executions_group', to='scrapers.scraper')),
            ],
        ),
        migrations.CreateModel(
            name='ScraperExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(verbose_name='Task Run UUID')),
                ('task_name', models.CharField(max_length=100, verbose_name='Task Name')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Start Datetime')),
                ('finish_datetime', models.DateTimeField(null=True, verbose_name='Finish Datetime')),
                ('keyword', models.CharField(max_length=1024, verbose_name='Keyword')),
                ('status', models.IntegerField(choices=[(1, 'STARTED'), (2, 'SUCCESS'), (3, 'FAILED')], default=1, verbose_name='Execution Status')),
                ('scraped_pages', models.IntegerField(null=True)),
                ('saved_records', models.IntegerField(null=True)),
                ('dropped_records', models.IntegerField(null=True)),
                ('error_log', models.TextField(null=True)),
                ('scraper_execution_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_executions_keywords', to='scrapers.scraperexecutiongroup')),
            ],
        ),
    ]
