# Generated by Django 3.2.8 on 2021-10-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperexecution',
            name='scraper_execution_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_executions_keywords', to='scrapers.scraperexecutiongroup'),
        ),
        migrations.AlterField(
            model_name='scraperexecutiongroup',
            name='scraper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_executions_group', to='scrapers.scraper'),
        ),
    ]
