name: CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      - name: Stylesheet check
        run: echo 'stylesheet check'

      - name: Build image
        run: docker build -t pcts-scraper .

  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  deploy_main:
    if: github.ref == 'refs/heads/main'
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
