name: CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      - name: Stylesheet check
        run: echo 'stylesheet check'

      - name: Build image
        run: docker build -t pcts-scrapers-api .

      - name: Run scraper tests
        run: |
          docker run\
            --volume ${PWD}/:/app\
            pcts-scrapers-api bash -c\
            "cd pcts_scraper_jobs && coverage run -m unittest discover && coverage xml"

      - name: SonarCloud Report coverage
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    needs: integration
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME_DEV: ${{ 'pcts-scrapers-dev' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku DEV
        run: |
          heroku git:remote -a $HEROKU_APP_NAME_DEV
          git push heroku HEAD:master

  deploy_prod:
    if: github.ref == 'refs/heads/main'
    needs: integration
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME_PROD: ${{ 'pcts-scrapers-prod' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku PROD
        run: |
          heroku git:remote -a $HEROKU_APP_NAME_PROD
          git push heroku HEAD:master
